# Yieldly Release Pipeline

name: '$(nugetPackageId) v$(majorVersion).$(minorVersion).$(patchVersion).$(Rev:r)' 

trigger: none

variables:
  buildConfiguration: 'Release'
  nugetPackageId: 'Yieldly'
  majorVersion: '0'
  minorVersion: '2'
  patchVersion: '0'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Update assembly info'
  inputs:
    Path: '$(Build.SourcesDirectory)/src/'
    FileNames: 'Yieldly/Yieldly.csproj'
    InsertAttributes: true
    WriteBOM: true
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: 'Build Yieldly .NET SDK'
  inputs:
    command: 'build'
    projects: 'src/Yieldly/Yieldly.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test Yieldly .NET SDK'
  inputs:
    command: 'test'
    projects: 'test/Yieldly.UnitTest/Yieldly.UnitTest.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack Yieldly .NET SDK Nuget package'
  inputs:
    command: 'custom'
    custom: 'pack'
    arguments: '$(Build.SourcesDirectory)/src/Yieldly/Yieldly.csproj --output $(Build.ArtifactStagingDirectory) --no-build /p:Configuration=$(buildConfiguration) /p:PackageID=$(nugetPackageId) /p:PackageVersion=$(AssemblyInfo.FileVersion) --verbosity Detailed'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Yieldly .NET SDK artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'